### ISSUE TITLE
Are non-unique census tract values correct?

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/mobilelatlong2cloud#5]
Similar to #4 but fewer in number, census tracts in the legacy application are only unique within a borough.  Here are census tract 75s:

![image](https://github.com/user-attachments/assets/2e9856a9-f443-4aed-81e3-c1ac9b56677c)

Again we will assume that this is correct and the users of the service know to combine the returned values with other layers to uniquely identify a census tract.  Alternative explanation A is that whoever loaded this data made a mistake.  Alternative B is that the users of this service don't care at all about what is returned.  Alternative C is that users of this service do not exist at all. 

@mlipper please review this as well at your convenience, thank you.

**Comment by mattyschell** [comment]
In addition to the non-unique values, the legacy application returns census tract "labels" instead of the 6 digit zero-padded census tract codes.  This is an odd choice for a service, but maybe the end users are more interested in display than processing.

31 instead of 003100
36.01 instead of 003601


![image](https://github.com/user-attachments/assets/c9ad2ac9-b625-4647-a892-410f09c6436d)

**Comment by mlipper** [comment]
Same answer as #4 unless I've mistakenly conflated two different issues as the same.

**Comment by mattyschell** [comment]
@mlipper please see this second part of issue 5, thanks!

https://github.com/mattyschell/mobilelatlong2cloud/issues/5#issuecomment-2236484639

**Comment by mlipper** [comment]
Hmmm. That does seem strange. I wonder if there's an erroneous data conversion there. E.g., Used to be VARCHAR now number. However, that doesn't really make sense because how would the decimal point get there?

My guess is that this, like most of the other weirdness, was a client feature request. Back in those days, we were much more accommodating about adding presentation logic to backend data services.

I'll try to sift through our internal git repo's history to see if there's any clues.

**Comment by mattyschell** [comment]
Closing this issue.  Replacing with #18 to specifically question labels vs codes
